- hosts: all
  tasks:
    - name: Install OpenVSwitch
      apt:
        name: openvswitch-switch
        update_cache: true
        state: present
      when: ansible_distribution == "Ubuntu"
      retries: 3
  roles:
    - prereq

- hosts: masters
  become: true
  gather_facts: no
  roles:
    - k8s/master

- hosts: workers
  become: true
  gather_facts: no
  roles:
    - k8s/worker

- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Create OVS Bridge
      command: ovs-vsctl add-br br1
      register: create_br_result
      changed_when: '"already exists" not in create_br_result.stderr'
      failed_when: create_br_result.rc != 0 and "already exists" not in create_br_result.stderr

- hosts: masters
  become: true
  gather_facts: no
  tasks:
    - name: Create VXLAN interfaces
      loop: "{{ groups['workers'] }}"
      loop_control:
        index_var: index
      command: ovs-vsctl add-port br1 vxlan-{{index}} -- set Interface vxlan-{{index}} type=vxlan options:remote_ip={{item}}
      register: create_vxlan_result
      changed_when: '"already exists" not in create_vxlan_result.stderr'
      failed_when: create_vxlan_result.rc != 0 and "already exists" not in create_vxlan_result.stderr

- hosts: workers
  become: true
  gather_facts: no
  tasks:
    - name: Create VXLAN interfaces
      loop: "{{ groups['masters'] }}"
      loop_control:
        index_var: index
      command: ovs-vsctl add-port br1 vxlan-{{index}} -- set Interface vxlan-{{index}} type=vxlan options:remote_ip={{item}}
      register: create_vxlan_result
      changed_when: '"already exists" not in create_vxlan_result.stderr'
      failed_when: create_vxlan_result.rc != 0 and "already exists" not in create_vxlan_result.stderr
