- hosts: all
  tasks:
    - name: Update Package Cache (apt/Ubuntu)
      tags: always
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
    - name: Install OpenVSwitch
      ansible.builtin.package:
        name: openvswitch-switch
        state: present
  roles:
    - prereq
    - download

- hosts: masters
  become: true
  gather_facts: no
  roles:
    - k3s/master

- hosts: workers
  become: true
  gather_facts: no
  roles:
    - k3s/worker

- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: Create OVS Bridge
      command: ovs-vsctl add-br br0
    - name: Create VXLAN interfaces
      loop: "{{ groups['all']|difference([inventory_hostname]) }}"
      command: ovs-vsctl add-port br0 vxlan-{{item.ansible_hostname}} -- set Interface vxlan type=vxlan options:remote_ip={{item.ansible_default_ipv4.address}}
