piVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-injector
  namespace: kuma-system
spec:
  selector:
    matchLabels:
      app: kuma-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: kuma-injector
    spec:
      serviceAccountName: kuma-injector
      containers:
        - name: kuma-injector
          image: kumacontrol/kuma-injector:latest
          args:
            - "--tls-cert-file=/certs/tls.crt"
            - "--tls-private-key-file=/certs/tls.key"
            - "--mesh=kuma"
            - "--dataplane-namespace=default"
          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        - name: certs
          secret:
            secretName: kuma-injector-certs

