apiVersion: v1
kind: Pod
metadata:
  name: samplepod-1
  annotations:  
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "ovs-br1",
          "ips": ["10.10.10.1/24"]
        }
]'
spec:
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-2
  annotations:  
    k8s.v1.cni.cncf.io/networks: '[
        {
          "name": "ovs-br1",
          "ips": ["10.10.10.2/24"]
        }
]'
spec:
  containers:
  - name: samplepod
    command: ["sleep", "99999"]
    image: alpine