apiVersion: v1
kind: Pod
metadata:
  name: wrk
  annotations:  
    k8s.v1.cni.cncf.io/networks: '[{"name": "ovs-br1","ips": ["192.168.1.1/24"]}]'
spec:
  containers:
  - name: wrk
    image: markmckessock/wrk
    command: ["/bin/bash", "-c", "apt update && apt install -y iproute2 iputils-ping curl && sleep 36000"]
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - wikijs
          weight: 100