apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  waf.conf: |
    # Nginx configuration for both HTTP and SSL

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 80;
        server_name 192.168.1.3
                    192.168.1.2;
        set $always_redirect off;

        location / {
            client_max_body_size 0;

            if ($always_redirect = on) {
                return 301 https://$host$request_uri;
            }

            proxy_set_header Host $host;
            proxy_set_header Proxy "";
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_http_version 1.1;
            proxy_buffering off;
            proxy_connect_timeout 60s;
            proxy_read_timeout 36000s;
            proxy_redirect off;

            proxy_pass_header Authorization;
            proxy_pass http://wikijs.default.svc.cluster.local:3000;
        }

        # include includes/location_common.conf;

    }
